ifdef::env-github[{set:link-ext:adoc}]
ifndef::env-github[{set:link-ext:html}]

DCS-BIOS is a community-maintained `Export.lua` file for use with http://www.digitalcombatsimulator.com/[DCS: World].
It provides a stable, documented interface for external hardware and software to interact with the clickable cockpit of a DCS: World aircraft.

== For Panel Builders

You don't need to be a programmer or electrical engineer.
The link:Scripts/DCS-BIOS/doc/userguide.{link-ext}[DCS-BIOS User Guide] will show you step by step how to connect your panel to DCS using DCS-BIOS and the beginner-friendly http://arduino.cc[Arduino microcontroller platform].
You don't have to write any program code yourself.

== For Software Developers

The link:Scripts/DCS-BIOS/doc/developerguide.{link-ext}[Developer Guide] explains how to connect to and interpret the DCS-BIOS export data stream and how to send commands to DCS-BIOS to operate controls inside the cockpit.

== Is My Aircraft Supported?

Currently, DCS-BIOS supports the following aircraft modules:

* A-10C (FSF-Ian)
* UH-1H (FSF-Ian)
* MiG-15Bis (contributed by BlackLibrary)
* MiG-21Bis (contributed by wraith444)
* Ka-50 (contributed by airtom)
* Mi-8 (contributed by ArturDCS)
* F-86F (contributed by ArturDCS)
* FW-190 (contributed by ArturDCS)
* Bf-109-K-4 (contributed by ArturDCS)
* Spitfire
* P-51D (contributed by pdmarsh)
* TF-51D (contributed by pdmarsh, ArturDCS)
* AJS-37 (contributed by pdmarsh extended by BlackLibrary,ArturDCS) 
* L-39ZA/C (contributed by kadda11)
* F-5E-3 (contributed by geebeer2, extended by BlackLibrary,Capt_Zeen)
* M-2000C (contributed by Exo7)
* F/A-18C (contributed by AndrewW)
* SA 342 (all Versions)
* AV8BNA (contributed by BlackLibrary)
* A-4E-C (contributed by BlackLibrary){ get the Mod here: https://forums.eagle.ru/showthread.php?t=224989 }
* MB-339PAN (contributed by BlackLibrary){ get the Mod here: http://www.freccetricolorivirtuali.net/mod%20ftv.htm }
* NS430 (contributed by Capt_Zeen, extended by Imp)
* All FlamingCliff3 Modules (A-10A;F-15C;J-11A;MiG-29A;
  MiG-29S;Su-25;Su-25T;Su-27;Su-33) but only supported with 
  CommonData like ALT, HDG,...

If you want to add support for another module, please get in touch.

== Mod Support

If you want to add a FlamingCliff3 based Mod (eg. VSN_Mod Planes) for commondata suport, you must follow
these instructions:

Add at the bottom  in \DCS-BIOS\lib\AircraftList.lua

a("PlaneName", false)

To get the correct Plane Name, open the control-reference page while you fly that plane. 
In MetadataStat you find the Plane Name.

== For setting up the Control-reference Page:

1. Install Google Chrome
2. Chrome -> "Settings" -> "More Tools" -> "Extensions", check "Developer mode"
3. Click "Load unpacked extension..." and choose your "C:\Users\<username>\Saved Games\DCS\Scripts\DCS-BIOS\doc" folder
4. A new extension "DCS-BIOS Control Reference Live Preview" 
   will be visible under "Apps".
5. Exit "Settings"
6. Click "Apps". Your DCS-BIOS extension be there. From there you can see the controls change as you fly and manipulate the cockpit. 

Remember to refresh the page if you restart a mission so that Chrome gets a new connection to DCS-BIOS.

Video: https://www.youtube.com/watch?v=MoVoa-BUOkQ

== Contribute

If you have a question or found a bug, please https://github.com/dcs-bios/dcs-bios/issues/new[open an issue on the GitHub issue tracker].

If you want to contribute code or documentation, please send a pull request on GitHub.

== License

DCS-BIOS is released under a slightly modified Simple Public License 2.0 (think "a version of the GPL readable by mere mortals"). Please see `DCS-BIOS-License.txt`.

The copy of `socat` that comes with DCS-BIOS is licensed under the GPLv2 (see `socat/COPYING`).
