ifdef::env-github[{set:link-ext:adoc}]
ifndef::env-github[{set:link-ext:html}]

== Flightpanel DCS-BIOS fork

DCS-BIOS is a `Export.lua` file for use with http://www.digitalcombatsimulator.com/[DCS: World].
It provides a stable, documented interface for external hardware and software to interact with the clickable cockpit of a DCS: World aircraft.

This Version is not only for Flightpanels, its like the normal DCS-BIOS version before the BIOS-HUB versions.
Works also for Pit Builders and Arduino users!

  If want to support us, You find infos at the bottom of this page!
  With that money, we buy the planes to integrade them in Flightpanel DCS-BIOS fork.
  
- Release/Prerelease are mostly for the stable version of DCS. 
- DCS Beta Users should use the master branch of the fork. _(Start a Flight before Programming to update the json Files)_
- Arduino Users should download the `Source code(zip)` on the Release page to get all needed files
- Flightpanel users download the `DCS-BIOS_0.7.XXX.zip`

Problems/Infos see our Wiki: https://github.com/DCSFlightpanels/DCSFlightpanels/wiki[DCS-Flightpanel/DCSBIOS Wiki]

https://github.com/DCSFlightpanels/dcs-bios/blob/master/Scripts/DCS-BIOS/doc/DCS-BIOS-FLIGHTPANELS.pdf[Quick Setup Guide]

== For Panel Builders

You don't need to be a programmer or electrical engineer.
The link:Scripts/DCS-BIOS/doc/userguide.{link-ext}[DCS-BIOS User Guide] will show you step by step how to connect your panel to DCS using DCS-BIOS and the beginner-friendly http://arduino.cc[Arduino microcontroller platform].
You don't have to write any program code yourself.

== For Software Developers

The link:Scripts/DCS-BIOS/doc/developerguide.{link-ext}[Developer Guide] explains how to connect to and interpret the DCS-BIOS export data stream and how to send commands to DCS-BIOS to operate controls inside the cockpit.

== Is My Aircraft Supported?

Currently, DCS-BIOS supports the following aircraft modules:

* **A-4E-C** _(contributed by Dehuman, revised by WarLord) { get the Mod here: https://github.com/heclak/community-a4e-c[GitHub] }_
* **A-10C / A10C-II** _(contributed by FSF-Ian, extended by WarLord) (use A-10C for All Versions)_
* **A-29B** _(contributed by WarLord) { get the Mod here: https://github.com/luizrenault/a-29b-community[GitHub] }_
* **AH-6J** _(contributed by WarLord) { get the Mod here: https://forums.eagle.ru/showthread.php?t=267143[Helicopter EFM Demo in ED Forums] }_
* **AH-64D** _(contributed by WarLord)_
* **AJS-37** _(contributed by pdmarsh extended by WarLord,ArturDCS,Matchstick)_
* **Alphajet** _(contributed by WarLord) { get the Mod here: http://www.jetesons.com/telechargement.html[JET E SONS] }_
* **AV8BNA** _(contributed by WarLord,Matchstick)_
* **Bf-109-K-4** _(contributed by ArturDCS)_
* **C-101CC / EB** _(contributed by WarLord,cdpkobra) (use C-101 for All Versions)_
* **Christen Eagle II** _(contributed by WarLord,cdpkobra)_
* **Edge-540** _(contributed by WarLord) { get the Mod here: http://virtualairrace.com/downloads/[Website of VIRTUAL AIR RACING SERIES] }_
* **Extra-330SR** _(contributed by WarLord) (use Edge-540) { get the Mod here: http://virtualairrace.com/downloads/[Website of VIRTUAL AIR RACING SERIES] }_
* **F-14B / A** _(contributed by WarLord,ArturDCS,Bullitt) (use F-14 for All Versions)_
* **F-16C** _(contributed by WarLord,cdpkobra,Matchstick,BuzzKillington)_
* **F-22A** _(contributed by WarLord) { get the Mod here: https://fsoutlet.com/f22/[Website of Flight Sim Outlet] }_
* **F-5E-3** _(contributed by geebeer2, extended by WarLord)_
* **F-86F** _(contributed by ArturDCS)_
* **F/A-18C** _(contributed by AndrewW)_
* **FW-190-A8** _(contributed by WarLord,MD44)_
* **FW-190-D9** _(contributed by ArturDCS)_
* **I-16** _(contributed by WarLord,NightStalker)_
* **JF-17** _(contributed by WarLord,cdpkobra)_
* **Ka-50** _(contributed by airtom)_
* **L-39ZA / C** _(contributed by kadda11, revised by WarLord) (use L-39 for All Versions)_
* **M-2000C** _(contributed by Exo7,ArturDCS,Matchstick)_
* **MB-339PAN** _(contributed by WarLord) { get the Mod here: http://www.freccetricolorivirtuali.net[Frecce Tricolori Virtuali] }_
* **Mi-8** _(contributed by ArturDCS,revised by WarLord)_
* **Mi-24P** _(contributed by WarLord,BaD CrC)_
* **MiG-15bis** _(contributed by WarLord,Steve Gee)_
* **MiG-21Bis** _(contributed by wraith444)_
* **Mosquito FB Mk.VI** _(contributed by WarLord)_
* **NS430** _(contributed by Capt_Zeen, extended by Imp, revised by Celemourn)_
* **P-47D** _(contributed by WarLord and Donators) (use P-47D for All Versions)_
* **P-51D** _(contributed by pdmarsh)_
* **Spitfire** _(revised by WarLord)_
* **SA 342** _(all Versions; use SA342 for All)_
* **T-45** _(contributed by WarLord) { get the Mod here: https://forums.eagle.ru/topic/203816-vnao-t-45-goshawk/[VNAO T-45 Goshawk in ED Forums] }_
* **TF-51D** _(contributed by pdmarsh, ArturDCS) (use P-51D)_
* **UH-1H** _(contributed by FSF-Ian)_
* **Yak-52** _(contributed by WarLord,cdpkobra)_
* Externals for all Airplanes _(Speedbrake and Lights; Weight on Wheels Code from DeadMeat)_
* All Flaming Cliffs 3 Modules _(FC3) (A-10A; F-15C; J-11A; MiG-29A;
  MiG-29S; Su-25; Su-25T; Su-27; Su-33) (contributed by danvac, extended by WarLord)_
* Superbug Mod _(F-18 E+F+Growler)_
* Mods (FC3): **VSN-Mods, PAK-FA Project, Civil Aircraft Mod, Upuaut's Bell-47G, Mirage F.1, SU-30 FAMILY PROJECT, MIG-23UB Project,
              Virtual Cockpits, AC-130**
  
  Use always the latest version of the Mods!
  
  For DCS Flightpanels: 
  FC3 are only supported with Keyemulator. But some Exports can made as Strings (FC3.lua) and CommonData 

If you want to add support for another module, please get in touch.(see below)

== Mod Support

If you want to add a FC3 based Mod (eg. VSN_Mod Planes) for commondata suport, you must follow
these instructions:

Add at the bottom  in \DCS-BIOS\lib\AircraftList.lua

a("PlaneName", false)

To get the correct Plane Name, open the control-reference page while you fly that plane. 
In MetadataStat you find the Plane Name.

== For setting up the Control-reference Page:

1. Install Google Chrome
2. Copy in the AddressBar `chrome://extensions/`, check "Developer mode" top right corner.
3. Click "Load unpacked extension..." and choose your "C:\Users\<username>\Saved Games\DCS\Scripts\DCS-BIOS\doc" folder
4. A new extension "DCS-BIOS Control Reference Live Preview" 
   will be visible under "Apps". `chrome://apps/`
5. Exit "Settings"
6. Start DCS, load a Mission and jump in a Plane
7. Click "Apps" in your Browser. Your DCS-BIOS extension be there. From there you can see the controls change as you fly and manipulate the cockpit. 

  Remember to hit the Refresh Button after you restart/change a mission, so Chrome gets a new connection to DCS-BIOS.
  
== socat

There are 2 socat versions, 32 and 64 bit. Choose that version that fits best for you. 
The files in the zip File must be unzipped direct in the socat folder.

  The path must be: /socat/socat.exe

== Video Tutorials

https://www.youtube.com/channel/UCwECFPfC3QJiNYS5fskF2vg/[DCS-BIOS Channel on Youtube]

== Contribute

If you have a question or found a bug, please https://github.com/DCSFlightpanels/dcs-bios/issues[open an issue on the GitHub issue tracker].

If you want to contribute code or documentation, please send a pull request on GitHub.

== License

The https://github.com/dcs-bios/dcs-bios[orginal DCS-BIOS] was programmed by [FSF]Ian. This is a Fork of his older Repositorie, where we made some additions and changes to it.

DCS-BIOS is released under a slightly modified Simple Public License 2.0 (think "a version of the GPL readable by mere mortals"). Please see `DCS-BIOS-License.txt`.

The copy of `socat` that comes with DCS-BIOS is licensed under the GPLv2 (see `/Programs/socat/COPYING`).

== Support

* Here you find our https://discord.gg/5svGwKX[DCSFlightpanels Discord Server]
* Here you find the https://github.com/DCSFlightpanels/DCSFlightpanels[DCSFlightPanels Software]
* Here you find the https://github.com/DCSFlightpanels/DCS-Flightpanels-Profiles[DCS-Flightpanels-Profiles]
* Here you find the https://github.com/DCSFlightpanels/dcs-bios-arduino-library[DCSFlightPanels arduino-library]

* If you want to support us: https://www.paypal.me/FPDCSBIOS[Here you can Donate.] 

                      (100% of donations are spent on acquiring new planes, this to keep the project alive and up to date)
