contact_links:
  - name: Community Support (GitHub Discussions)
    url: https://github.com/DCS-Skunkworks/dcs-bios/discussions/categories/q-a
    about: Please ask and answer questions here so that others may benefit in the future.
  - name: Community Support (Discord)
    url: https://discord.gg/5svGwKX
    about: You may also reach out on Discord if you prefer.
