= DCS-BIOS User Guide
:toc: right
:icons: font

Welcome to the DCS-BIOS User Guide.

This manual will explain how you can use DCS-BIOS to connect the clickable cockpit of a DCS: World aircraft to real-world hardware such as toggle switches, push buttons, rotary encoders, potentiometers and displays.

NOTE: If you want to add a new aircraft module or use your own software with DCS-BIOS, please refer to the Developer Guide.

== Introduction

So you want to build a panel for your DCS: World aircraft.
Whether you own a CNC machine or just a drill and a hot glue gun, you probably have some idea of how to use the tools available to you to mount controls such as push buttons, toggle switches, rotary encoders and potentiometers to a faceplate.

Once you have done that, you will have to find a way to connect those controls to your DCS: World aircraft.
If that aircraft is the A-10C, read on to find out if DCS-BIOS is right for you.

=== Why Use DCS-BIOS?

If you read the Home Cockpits section on the ED forums, you will find several ways to connect a panel to DCS.
If DCS-BIOS is yet another way to do the same thing, why should you use it over the alternatives?

.DCS-BIOS is easy to use.

You may have heard of people learning Lua to write their own `Export.lua` file and trying to figure out which _Device ID_, _command_ and _argument number_ correspond to a specific switch by reading the Lua code that comes with DCS: World.

DCS-BIOS deals with all of that so you don't have to. *If you can connect two wires together, copy and paste text and follow step-by-step instructions, you can make a functioning panel.*

.Everything is documented
DCS-BIOS comes with full documentation that is aimed at beginners.
You do not have to be a programmer or an electrical engineer to use it.
After you read this User Guide, you will be able to connect a simple panel to DCS.

If you do have a programming background or simply want to know more, we have a Developer Guide that explains the internals in greater detail.

.It will not impact performance

We did not notice any change in FPS when testing DCS-BIOS.
The additional computation it requires of DCS is negligible.

.Your panel will continue to work when DCS: World is updated

DCS-BIOS isolates you from changes in DCS: World.
Most updates to DCS: World will not affect it at all.
If ED does make a change that breaks something, we will release an updated version of DCS-BIOS.
Your panels will always stay the same.

.Efficient protocol design

DCS-BIOS sends data out of DCS in a very efficient way.
Your indicators will not start to stutter when a lot is changing at once, such as when pressing the signal lamp test button, spooling up the engines, or when half your caution lights panel is blinking after a SAM hit.

.Take advantage of the Arduino ecosystem

DCS-BIOS was designed to work well with the http://www.arduino.cc[Arduino family of microcontroller boards.]

By using a popular, general-purpose microcontroller development board instead of designing a custom PCB, we benefit from mass production and economics of scale.
Suitable boards can be bought for about $25 from the official Arduino store, about half of that if you look on eBay or Amazon, and if you are willing to wait a few weeks for delivery from China you can get started for less than $5.

The popularity of the Arduino platform has also spawned a lot of online tutorials, guides and blog posts.
No matter what device you want to connect to your Arduino board, someone out there has probably already done it before and documented the results.



== Connecting your First Panel

After working through this section, you will have connected your first panel to DCS-BIOS.

=== Before you start

Make sure you have the following.

==== Skills

* Have a basic understanding of what an *electric circuit* is.
* Know what a *short-circuit* is, why it is a Bad Thing(TM) and how to avoid creating one by accident
* Have some way to make electrical connections. That can mean a "breadboard" and jumper wires, a soldering iron, a wire wrap tool, ...

==== Equipment
We will assume you have access to the following:

* A computer that has DCS: World installed, can access the internet and has a free USB port
* An Arduino board
* A push button
* A way to connect your push button to your Arduino


=== Step 1: Setting up DCS-BIOS

. Download the latest stable release of DCS-BIOS from https://github.com/jboecker/dcs-bios/releases[GitHub] and extract the ZIP file somewhere on your hard drive

. Open a new Explorer window (for example by opening "My Computer"), paste the following into the address bar and press return:
----
%USERPROFILE%\Saved Games\DCS
----
This should take you to your DCS configuration folder (its subfolders should include `Logs` and `Missions`).

If you don't see a `Scripts` subfolder, copy the entire `Scripts` folder where you extracted DCS-BIOS to this directory and skip to the next step.

If you do have a `Scripts` subfolder, copy the contents of the `Scripts` folder from where you extracted DCS-BIOS into your existing `Scripts` folder instead.

If you also have an existing `Export.lua` file, do not copy the `Export.lua` file from the DCS-BIOS download.
Instead, open your existing `Export.lua` file in a text editor such as Notepad++ and append the following line:
[source,lua]
----
dofile(lfs.writedir()..[[Scripts\DCS-BIOS\BIOS.lua]])
----

NOTE: DCS-BIOS is now installed and enabled.
If you want to verify it, you can start up an A-10C, run `multicast-console.cmd` from your DCS-BIOS download directory, type `AHCP_CICU TOGGLE` into the console window and press return.
That should toggle the CICU switch in your virtual cockpit.

=== Step 2: Connecting your LED and button

* Connect your push button between Arduino digital pin 10 and ground.

* Connect your LED and current limiting resistor between Arduino digital pin 13 and ground.

=== Step 3: Set up the Arduino IDE

* Download and install the Arduino IDE http://arduino.cc/en/Main/Software[from the Arduino website.]

* Download the https://github.com/jboecker/dcs-bios-arduino-library/releases[DCS-BIOS Arduino library] from GitHub.
You do not have to extract it.
+
. Start the Arduino IDE
. Click `Sketch -> Import Library -> Add Library...` and select the ZIP file you downloaded
. Close and re-open your Arduino IDE

=== Step 4: Create a program for your Arduino board

Congratulations, you have completed all of the one-time setup steps.
For each panel that you create, you will have to do steps 4 and 5.

In this step, you are going to create a program for your Arduino board.
That program will read the state of connected switches and report changes to DCS-BIOS.
It will also interpret the data that DCS-BIOS sends to control LEDs, servo motors, or even displays.

NOTE: Arduino programs are also referred to as "sketches".

Click File -> Examples -> DcsBios -> TemplateSketch to open the template program that comes with the DCS-BIOS Arduino library.

To complete the template program, you are going to copy code snippets from the reference documentation.

. Open the reference documentation in a browser by double-clicking the file `protocol-reference.html` which is located in the `doc` folder in your DCS-BIOS download.
. If you see a red warning followed by a bunch of nonsense, you need to enable JavaScript in your web browser and reload the page.

The reference documentation lists every switch, push button and rotary knob that DCS-BIOS knows about.
To show only those that belong to the Up Front Controller, type `UFC` into the `Category Filter` box at the top.

The first entry should be the one for the Master Caution Light.
Note that it comes with two code snippets.

Because you want to connect a LED, copy the second snippet to your Arduino sketch.

In the reference documentation, `PIN` is highlighted in red in the example code.
That means you have to replace that with your own value, in this case the pin number you have connected the LED to.
In your sketch, replace `PIN` with `13` so you end up with this:
[source,c++]
----
DcsBios::LED masterCaution(0x108e, 0x0008, 13);
----

Scroll down to the `UFC_MASTER_CAUTION / Master Caution Reset` entry.
This represents the push button that resets the master caution warning.

In the reference documentation, you see it has example code for a `DcsBios::Switch2`, which is used for toggle switches and push buttons.
Again, copy the example code snippet to your sketch.
We connected the push button to pin `10` earlier, so replace `PIN` with `10`.

Now the start of your template program should look like this:
[source,c++]
----
#include <DcsBios.h>
#include <Servo.h>

/**** Make your changes after this line ****/

DcsBios::LED masterCaution(0x108e, 0x0008, 13);
DcsBios::Switch2 ufcMasterCaution("UFC_MASTER_CAUTION", 10);

/**** In most cases, you do not have to change anything below this line ****/

----

Your program is finished.
Click `File -> Save As` to save it under a new name.

NOTE: The Arduino IDE prevents you from saving changes to a library example.
You will have to save your changes under a new name.

=== Step 5: Copy your program to your Arduino board

Now that your Arduino sketch is done, you need to load it onto your board.

The details may vary for different Arduino boards.
The Arduino website has detailed guides for each individual board.

After loading your program onto your Arduino board, you can close the Arduino software.

=== Step 6: Test your new panel

DCS-BIOS comes with a script that connects a serial port (which is what your Arduino board uses to talk to the PC) to the DCS-BIOS data stream.

Open `connect-serial-port.cmd` from your DCS-BIOS download in a text editor and locate the line that starts with `COMPORT=`.
Replace the number with the COM port number you used to program your Arduino board and save the file.

Now double-click `connect-serial-port.cmd`.
A console window should pop up.
Leave it open.

You can now start DCS and try your new panel in action!




== A Closer Look at The DCS-BIOS Arduino Library

This tutorial will show you how to read the DCS-BIOS reference documentation to create a sketch for any panel in the cockpit.

It will cover all of the different control types that are supported by the Arduino library.

=== The MasterCaution Example Sketch

This section takes a closer look at the different parts of the MasterCaution example sketch.

[source,c++]
----
/* Include neccessary libraries */ <1>
#include <DcsBios.h>
#include <Servo.h>

/* Define connected controls */ <2>
DcsBios::Switch2 masterCautionBtn("UFC_MASTER_CAUTION", 10);
DcsBios::LED masterCautionLED("MASTER_CAUTION", 13);

/* Standard boilerplate code follows */
DcsBios::ProtocolParser parser; <3>

void setup() {
  Serial.begin(500000); <4>
}

void loop() {
  // feed incoming data to the parser
  while (Serial.available()) {
      parser.processChar(Serial.read()); <5>
  }
  
  // poll inputs
  DcsBios::PollingInput::pollInputs(); <6>
}

void sendDcsBiosMessage(const char* msg, const char* arg) { <7>
  Serial.write(msg);
  Serial.write(' ');
  Serial.write(arg);
  Serial.write('\n');
}

void onDcsBiosMessage(const char* msg, const char* arg) { <8>
  
}
----

<1> Include the neccessary header files.
This ensures that the Arduino IDE will bring in the required libraries during the compilation process.
Even if your sketch does not use the `ServoOutput` class you still have to include `Servo.h`.
Otherwise your sketch will not compile.

<2> Tell the library what types of controls are connected to your Arduino.
DCS-BIOS knows how to handle push buttons, toggle switches, rotary encoders, rotary switches, potentiometers, LEDs and servo motors.
If you want to use one of these control types, refer to the next section to learn how to read the reference documentation and find out what to put here.

<3> Create an object of type `DcsBios::ProtocolParser`.
We will need this later.

<4> In the `setup()` function, we set up the serial port to run at a speed of 500000 bps.
This setting needs to match the one in `connect-serial-port.cmd`.
500000 is the fastest the Arduino can handle and is the default.

<5> In `loop()`, we read data from the serial port and feed it to the `DcsBios::ProtocolParser` we created above.

<6> We also need to call `DcsBios::PollingInput::pollInputs()`.
This causes the DcsBios library to check the state of all connected inputs such as push buttons, rotary encoders, etc. and send a message to your DCS computer if they have changed.

<7> The DcsBios Arduino library expects you to supply a function called `sendDcsBiosMessage` that knows how to send a message to your DCS computer.
In this case, we simply write the message to the serial port.

<8> The DcsBios Arduino library calls `onDcsBiosWrite` whenever it receives data from DCS.
This is the place to handle output when the DcsBios library does not have a pre-made class that fits your needs, for example when you want to connect a display for a radio frequency.
Even when it is empty, this function must exist.
The compiler will complain otherwise.

=== Using the Reference Documentation
Recall the following part from the MasterCaution example:
[source,c++]
----
DcsBios::Switch2 masterCautionBtn("UFC_MASTER_CAUTION", 10);
DcsBios::LED masterCautionLED("MASTER_CAUTION", 13);
----

Unless you are doing something more advanced such as connecting displays or using something other than a serial port to talk to your DCS computer, this is the only part you need to modify.

Even without knowing much about DCS-BIOS, you might have guessed that this says there is a push button connected to pin 10 that should operate the master caution button and that the LED on pin 13 should light up then the master caution button does.

But how do you know what to put here for other controls?
You will have to consult the reference documentation.

==== Locating the Reference Documentation

The reference documentation is included in the `doc/` subdirectory in the DCS-BIOS download.
Simply double-click `protocol-reference.html` to open it in your web browser.

NOTE: If you see a red warning at the top of the page followed by a bunch of gibberish, you need to enable JavaScript and reload the page.

==== Controls
In your virtual cockpit you will find lots of toggle switches, buttons and rotary knobs.
DCS-BIOS refers to them as controls.

Each control is identified by a unique identifier and is associated with a category, which is usually the panel it is found on in the virtual cockpit.

Some knobs in your cockpit are represented as two separate controls.
For example, the volume controls on the A-10C intercom panel have one DCS-BIOS control for the volume and a separate for the mute function.

==== Finding the Control You Are Looking For

Use the search boxes at the top of the page to quickly find what you are looking for.
You can filter by category, identifier and description.

==== Input Interfaces

Each DCS-BIOS control can support multiple _input interfaces_.
An _input interface_ allows you to control something in the cockpit by sending a message to DCS-BIOS.
For example, you can toggle the CICU switch in the A-10C by sending `AHCP_CICU TOGGLE`.

A message starts with the identifier of the control you want to manipulate, followed by a space, an _argument_, and a newline character.
Different input interfaces understand different arguments.

Depending on the type of input interface, the reference documentation will offer different snippets of example code.

.Types of input interfaces

set_state:: If a control supports the _set_state_ interface, its current state can be set by sending it a number as an argument.
For example, you can set the TACAN mode dial in the A-10C to the `A A REC` position by sending `TACAN_MODE 3`.
+
NOTE: The range of acceptable values is 0 to the maximum value of the control's first output.
+
The reference documentation will offer example code for a `DcsBios::RotarySwitch` and (in the case of two-position controls) a `DcsBios::Switch2`.

fixed_step:: If a control supports the _fixed_step_ interface, you can increase its position with an `INC` argument and decrease its position with an `DEC` argument.
+
The reference documentation will offer example code for a `DcsBios::RotaryEncoder`.

action:: This represents an action such as toggling a toggle switch or changing the X/Y digit of the TACAN channel.
+
The reference documentation will offer example code for a `DcsBios::ActionButton`.

variable_step:: If a control supports the _variable_step_ interface, you can increase or decrease its position by a certain amount by sending `+NUMBER` or `-NUMBER` as an argument, where `NUMBER` is an integer.
+
The reference documentation will offer example code for a `DcsBios::RotaryEncoder`.
The default step size is 3200.
You will need to experiment to get the right sensitivity.


==== Outputs

Each DCS-BIOS control can have multiple related _outputs_.
An _output_ represents a piece of information that is exported from DCS, for example the position of the flaps position indicator.

Outputs come in two types:

Integer outputs:: Most outputs are integers.
Each integer output has an associated maximum value and a minimum value of 0.
+
The reference documentation will offer code examples for `DcsBios::LED` and `DcsBios::ServoOutput` where appropriate.
+
The first code snippet for integer outputs is meant to be inserted into the `onDcsBiosWrite` function if the DCS-BIOS Arduino library cannot do what you want.
It shows you how to extract the value using the _mask_ and _shift_ values of the output.
+
NOTE: To learn about the meaning of the _address_, _mask_ and _shift_ value of an output, please refer to the developer guide.

String outputs:: Some values (such as radio frequencies) are exported as character strings.
The reference documentation will provide a code example that uses a `DcsBios::StringBuffer` to execute a piece of code whenever the value changes.
+
NOTE: Because there are many different types of displays (7-segment, character, graphical) and different ways to connect them to a microcontroller (direct, I2C, SPI), the DcsBios library does not include code to handle them.
For most common combinations of display type and connection method, you can find other Arduino libraries online that allow you to talk to them.


==== Copy and Paste Example Code

To use the example code from the reference documentation in your Arduino sketch, you first have to choose which code example to copy.
That depends on what type of control you want to connect.

For example, you might want to use a rotary switch for the TACAN mode dial in the A-10C and use the `DcsBios::RotarySwitch` code snippet. For the same control, you could also choose to use a rotary encoder.

After choosing a code example, copy it to your Arduino sketch (refer back to the MasterCaution example to see where to copy it) and replace all the parts in red with your own values (usually the pin numbers that this control is connected to).

Refer to the next section for more detailed information on the individual classes, including example circuits.


=== Classes to Handle Inputs
==== ActionButton

[source,c++]
----
DcsBios::ActionButton(char* message, char* argument, char* pin)
----

The ActionButton class is used to send a single command to DCS when its input pin goes low.

.Constructor Parameters
message:: The message that should be sent. Set this to the identifier of the control.
argument:: The argument that should be sent.
pin:: The number of the Arduino pin the button is connected to.

.Circuit
Connect a push button between the Arduino pin and ground.

.Reference Documentation Code Example
[source,c++]
----
DcsBios::ActionButton ahcpCicuToggle("AHCP_CICU", "TOGGLE", PIN);
----

.Code Examples
[source,c++]
----
DcsBios::ActionButton ahcpCicuToggle("AHCP_CICU", "TOGGLE", 10); // <1>
DcsBios::ActionButton decTacanMode("TACAN_MODE", "DEC", 11); // <2>
----
<1> A button on pin 10 that toggles the CICU switch
<2> A button on pin 11 that moves the TACAN Mode dial one position to the left

==== Switch2

[source,c++]
----
DcsBios::Switch2(char* message, char pin)
----

The Switch2 class handles inputs that have two states, such as toggle switches and push buttons.

.Constructor Parameters
message:: The message that should be sent. Set this to the identifier of the control.
pin:: The number of the Arduino pin the button or switch is connected to

.Circuit
Connect the toggle switch or push button between the Arduino pin and ground.

.Reference Documentation Code Examples
[source,c++]
----
DcsBios::Switch2 ahcpCicu("AHCP_CICU", PIN);
----

[source,c++]
----
DcsBios::Switch2 ufcHack("UFC_HACK", PIN);
----

==== RotarySwitch

[source,c++]
----
DcsBios::RotarySwitch(char* message, const byte* pins, char numberOfPins);
----

The RotarySwitch class handles rotary switches.

.Constructor Parameters
message:: The message that should be sent. Set this to the identifier of the control.
pins:: An array of pin numbers that the rotary switch positions are connected to.
The first pin number corresponds to state 0 of the input, the second to state 1, etc.
numberOfPins:: The length of the array passed in the `pins` parameter.

.Circuit
Connect the rotary switch so that it connects the Arduino pin for the currently selected position to ground.

.Reference Documentation Code Examples
[source,c++]
----
const byte aapSteerptPins[3] = {PIN_0, ... ,PIN_2};
DcsBios::RotarySwitch aapSteerpt("AAP_STEERPT", aapSteerptPins, 3);
----

.Example
[source,c++]
----
// A rotary switch that controls the A-10C steerpoint mode (FLTPLAN / MARK / MISSION)
// is connected to digital pins 10, 11 and 12
const byte aapSteerptPins[3] = {10, 11, 12};
DcsBios::RotarySwitch aapSteerpt("AAP_STEERPT", aapSteerptPins, 3);
----

==== Potentiometer

[source,c++]
----
DcsBios::Potentiometer(char* message, char pin);
----

The Potentiometer class handles potentiometers connected to an analog pin.

.Constructor Parameters
message:: The message that should be sent. Set this to the identifier of the control.
pin:: The number of the pin that is connected to the potentiometer.

.Circuit
Connect the outer pins of the potentiometer to +5V and ground.
Connect the middle pin to the Arduino.

To reverse the direction, swap +5V and GND.

.Reference Documentation Code Example
[source,c++]
----
DcsBios::Potentiometer cmscBrt("CMSC_BRT", PIN);
----

==== RotaryEncoder

[source,c++]
----
DcsBios::RotaryEncoder(const char* message, const char* decArg, const char* incArg, char pinA, char pinB);
----

The RotaryEncoder class handles standard rotary encoders.

.Constructor Parameters
message:: The message that should be sent. Set this to the identifier of the control.
decArg:: The argument that should be sent when the encoder is turned one step to the left.
incArg:: The argument that should be sent when the encoder is turned one step to the right.
pinA:: The first pin that is connected to the encoder.
pinB:: The second pin that is connected to the encoder.

.Circuit
Rotary encoders usually have three pins (the ones with an integrated push button have two extra pins for the button).
Connect the left pin to Arduino pin A, the middle pin to ground and the right pin to Arduino pin B.

To reverse the direction, either swap decArg and incArg or swap pinA and pinB.

.Reference Documentation Code Example
[source,c++]
----
DcsBios::RotaryEncoder tacan1("TACAN_1", "DEC", "INC", PIN_A, PIN_B);
----


=== Classes to Handle Outputs
==== LED
==== ServoOutput
==== StringBuffer

[source,c++]
----
DcsBios::StringBuffer<MAXLENGTH>(unsigned int address, void (*)(char*) callback)
----

The StringBuffer class is used to handle string outputs.

.Constructor Parameters
MAXLENGTH:: The maximum length of the string output
address:: The address of the string output
callback:: A function which accepts an argument of type `char*`.
This function will be called whenever the string output has changed.
It will be passed the new value as an argument.

.Reference Documentation Code Example
[source,c++]
----
void onUhfFrequencyChange(char* newValue) {
    /* your code here */
}
DcsBios::StringBuffer<7> uhfFrequencyBuffer(0x1170, onUhfFrequencyChange);
----

